### ISSUE TITLE
Crash upon world load

### ISSUE THREAD

**Issue by iamweirdie** [gbl/EasierCrafting#15]
Hello,

I installed easiercrafting-1.12-forge14.21.1.2387-1.2.jar and my instance crashed when i tried to load the world. it also spit out these logs.

https://paste.dimdev.org/ososucihok.mccrash
https://paste.dimdev.org/oyigabowor.mccrash

I hope this can be fixed soon.

**Comment by gbl** [comment]
At least as far as I can tell, this isn't a bug in easier crafting, as the stack trace doesn't have easier crafting in its trace, and easiercrafting doesn't do anything to tile entities, so it's unlikely to cause the ConcurrentModificationException. As you have a lot of mods, I'd assume something else is causing this.
