### ISSUE TITLE
[Suggestion]Add easier crafting for stone cutter

### ISSUE THREAD

**Issue by Harveykang** [gbl/EasierCrafting#17]

**Comment by gbl** [comment]
This probably applies to grindstone, fletching table, and loom, as well.

**Comment by gbl** [comment]
Just uploaded version 1.5.0 to curseforge (for Fabric 1.14.4 and 1.15, should work on other minor versions as well). Please try and leave feedback.

**Comment by Harveykang** [comment]
nice job<3, it's perfect!
