### ISSUE TITLE
GUI Compatibility with Roughly Enough Items

### ISSUE THREAD

**Issue by Nukiloco** [gbl/EasierCrafting#18]
When running REI with this mod, REI items overlap EasierCrafting's GUI. A quick fix is setting the config where the mod appears on the left side of the inventory. Problem is when you favorite a lot of items to the left, they start to overlap EasierCrafting's GUI again.

**Comment by gbl** [comment]
That's basically the reason why the mod has the left/right config thing, people with REI resp. other ?EI mods had the GUIs overlap. However, what else should I do? If some other mod takes all or most of the screen estate, there's no good place to display my GUI at.

**Comment by gbl** [comment]
From 1.16 on, the mod will only show its own GUI when REI is turned off (CTRL-O)

**Comment by Tsolval** [comment]
This bug is back with the 1.17 alpha versions of REI.
Minecraft Version: 1.17
Fabric Version: 0.11.6
Fabric API Version: 0.36.0
REI version: 6.0.262-alpha-fabric
Easier Crafting Version: 1.6.7
