### ISSUE TITLE
[Request] A way to scroll through the list of available recipes

### ISSUE THREAD

**Issue by MysticAura** [gbl/EasierCrafting#2]
Currently when you have the inventory items to make a ton of recipes, a bunch of the recipe groups end up off your screen. A way to scroll through would solve this issue.

My thought. Click a group name, that group opens to show the items in the group. This would keep things cleaner and more ordered. Expand/Collapse all groups, button toggle.

Allow searching by group name.

I really like this mod. It's helpful and a nice alternative for people. I look forward to seeing what advancements it makes in the near future

**Comment by gbl** [comment]
Not very pretty, but has been working for a while.
