### ISSUE TITLE
Incorrect scale when not maximized

### ISSUE THREAD

**Issue by 66Leo66** [gbl/EasierCrafting#20]
When using this mod while Minecraft is not maximized, the scale of the mod display is too large. Also, it seems that this mod is incompatible with therecipe book.
I'm not sure if this is caused by setting the "GUI Scale" in "Video Settings" option to a exact value(I set it to 2) instead of keeping it "Auto".
I'm not sure if it is related to #2 which too much craftable goes out of the game window.

![Screenshot1](https://i.loli.net/2020/03/13/x2i7hseklCXHbyG.png "Too much craftable")
![Screenshot2](https://i.loli.net/2020/03/13/bTZplAC6DdGYj7k.png "Incompatible with recipe book")

**Comment by gbl** [comment]
Sorry, but I can't do much about that - the mod needs some space to display, if you make the space that's needed by Minecraft too large, then the mod doesn't have space to display its own things.

This is why the mod has an option to disable the recipe book.

Without the recipe book, it only displays as much as it can; you can use the (admittedly very ugly) arrows at the top to scroll.
