### ISSUE TITLE
Disabling item access with Simple Storage Network mod 1.12.2

### ISSUE THREAD

**Issue by damiansz66** [gbl/EasierCrafting#23]
Trying to open storage request table will result in opening crafting table instead of my items.
![image](https://user-images.githubusercontent.com/40820407/82131770-1721a600-97d9-11ea-9153-3e7c935f245d.png)
![image](https://user-images.githubusercontent.com/40820407/82131772-1db01d80-97d9-11ea-808a-9208a1a56fad.png)

**Comment by gbl** [comment]
Wasn't able to reproduce this, until I installed FastWorkBench as well, which Simple Storage Network seems to plug in to. Try disabling that mod; it replaces the workbench GUI, as does mine, so they're fundamentally incompatible.

If you managed to get the error without FastWorkBench, please provide detailed instructions how to reproduce it, as I don't know those mods so don't know what I'm possibly missing. For example, what is that block that has the green crafting grid? I wasn't able to find it in creative tab for simple storage. What else needs to be connected?

**Comment by gbl** [comment]
undo accidential close

**Comment by damiansz66** [comment]
works well without fast workbench,
would be cool if it could use internal inventories like AE2 or Simple Storage Network to craft and show available recipes. ty for help
