### ISSUE TITLE
Crafting grid only fills haf / cant make ingot if gold block in inventory

### ISSUE THREAD

**Issue by Astro379** [gbl/EasierCrafting#24]
Q: having a problem here, as im standing in my gold farm and is producing gold block out of tons of gold nugget by breaking down chest and then craft nuggets into ingot and then into gold block

as im crafting ingots my crafting grid suddenly only get half full so i have to stop making and then close my inventory from the crafting bench and then open up again and start over, not the worst problem but then the mod have started to take the gold blocks i have made and want to turn them into 9 ingot and i cant make anymore ingot from nuggets as long i have the gold blocks in my inventory

is there a way to fix these issues ?

**Comment by gbl** [comment]
Explained a workaround on CF. When there's 2 different recipes for the same item - here: nuggets to ingots and blocks to ingots - and both can be crafted from existing inventory, then it's basically random which one gets shown.
