### ISSUE TITLE
Chest crash

### ISSUE THREAD

**Issue by ardentcrest** [gbl/EasierCrafting#25]
easiercrafting-1.16-fabric0.13.1-1.6.1.beta4.jar will crash client when clicking on chest or shulker box.

**Comment by gbl** [comment]
It doesn't do that for me - can you post a crash report somewhere, one that has the list of installed mods, please?

**Comment by ardentcrest** [comment]
in 1.16 crash client when clicking on chest or shulker box.
in 1.16.1 crashes before start up 
https://paste.ee/p/LwrcG

**Comment by gbl** [comment]
That paste has

easiercrafting-1.14.4-fabric0.4.2-1.5.0

though ...

**Comment by ardentcrest** [comment]
Ok sorry about that :) had remove wrong file when updating in multimc both had $(version) in version column

**Comment by gbl** [comment]
No worries, glad it was easy to resolve :)
However, the fact that it has ${version}, not the real version number, is a bug, thanks for pointing this out.

**Comment by gbl** [comment]
There's an mcmod.info in that jar that I somehow didn't delete when moving away from Forge. Doh.

**Comment by gbl** [comment]
Removed the mcmod.info .. was in a few other mods as well.
