### ISSUE TITLE
Crafting Table doesn't update on client

### ISSUE THREAD

**Issue by SwanX1** [gbl/EasierCrafting#26]
When something is normally clicked (not shift-clicked), the items go into the crafting table, but don't display an output. Packets are sent, confirming that crafting is completed, and quitting the crafting GUI will update your inventory.

Edit: Error occurs when crafting only one item, and occurs on every crafting screen.

**Comment by Madis0** [comment]
Can confirm on MC 1.16.1, EC 0.13.1 b 5

**Comment by SwanX1** [comment]
Hmm... seems to be fixed in version 0.13.1-1.6.1.beta5
