### ISSUE TITLE
Crash probably because of conflicting mods

### ISSUE THREAD

**Issue by allethargic** [gbl/EasierCrafting#27]
Crashing only with EasierCrafting installed. Log file:
[latest.log](https://github.com/gbl/EasierCrafting/files/5015353/latest.log)

**Comment by gbl** [comment]
From the log file, you're using 

easiercrafting@**1.16.2-pre1**-fabric0.16.3-1.6.1.beta6

which is for the  prerelease of 1.16.2, but it seems like you're using MC 1.16.1.

For 1.16.1, please use this: https://www.curseforge.com/minecraft/mc-mods/easiercrafting/files/2992304

**Comment by allethargic** [comment]
My bad, I kinda lost myself trying to create modpack. Thanks for answer.
