### ISSUE TITLE
Loom Recipes

### ISSUE THREAD

**Issue by HappyClownn** [gbl/EasierCrafting#28]
Recently I was dealing with banners in the game. The mod you made was very useful for me and I was wondering how to use it better.

The letter banners that came with the mod attracted my attention and I did some research on the internet to find better ones.

However, I wanted to delete your mod's own banners from (config -> loomrecipes) and use the different letter banners I found on the internet. When I tried to delete the original banners of the mod, I saw that it was recreated while the game was starting.

Is there any way I can disable this feature?

**Comment by gbl** [comment]
When the mod extracts its own banners, it won't overwrite existing files. So you can, for example, replace the letter_X.lr with your own file, and the mod won't overwrite it. It's just that when the file doesn't exist, the mod recreates it.

Likewise, you can delete all (or almost all) entries from the loomrecipes.zip file (which the mod creates in config), as long as the zip file exists, the mod won't overwrite it, and only extract loom patterns from that reduced file. If you remove the zip completely, the mod will recreate it the next time it starts.

**Comment by HappyClownn** [comment]
Thanks for answer!
