### ISSUE TITLE
issue with shulker boxes

### ISSUE THREAD

**Issue by dragoneli1** [gbl/EasierCrafting#31]
when you open your inventory with a shulker box and a dye of any colour in it, it will crash your client. 1.16.2

**Comment by gbl** [comment]
Thanks for reporting this!
I don't have time to look into it right now, but this is probably because the recipe gets added in a non-standard way. As a workaround,  turning off the "allow special recipes" option should make the crash go away as it won't try to add a shulker coloring recipe.

**Comment by Kylebartaous** [comment]
Also, having paper & gunpowder in your inventory would crash you, then trying to make firework rockets.


Info:
Minecraft version: 1.16.1
Fabric loader version: 0.9.2 build 206 for version 1.16.1
Fabric API version: 0.17.0 build 386 for version 1.16.1
Eaisercrafting mod version: 1.16-fabric- 13.1-1.6.3
I also do have Rei mod installed

here's a crash log:  https://pastebin.com/D0WUe6Rn

**Comment by gbl** [comment]
Yes. Same bug. And it happens with arrows+lingering potions as well, but only with the crafting table, because you can't poison arrows from your inventory. Working on a fix right now.

**Comment by Kylebartaous** [comment]
ok cool thx

**Comment by gbl** [comment]
Just uploaded 1.6.4 for 1.16/1.16.1 and for 1.16.2 on CF, should be approved in a few minutes.
