### ISSUE TITLE
EC 1.6.7 with refresh=false broken

### ISSUE THREAD

**Issue by MeeniMc** [gbl/EasierCrafting#35]
I just installed the all fresh new release, but it doesn't work properly with `requestInventoryRefresh=false` (the default). 

In this mode, left clicking an item fills the crafting table with the recipe and leaves the table in a glitched state. The item has been produced (if you close inventory, reopen inventory both recipients and results are updated), but the produced item doesn't appear in the inventory yet, and the recipe remains in the table, as-if it had not done the crafting. Removing the recipients causes an update and make the produced item appear. 

With the option set to 'on' it appears to behave exactly as before, not sure what the new option do. 

This is a singleplayer world. Didn't test on servers.

**Comment by gbl** [comment]
MC 1.17 changes the way how server and client interact resp. inventory changes, so all the fuzz isn't needed anymore. Closing this now.
