### ISSUE TITLE
Inventory and crafting interface not updating properly 

### ISSUE THREAD

**Issue by rmalagon238** [gbl/EasierCrafting#36]
I noticed that after crafting something ex: planks, that any recipes that used planks would not show up until i closed reopened my inventory. I turned on the "request inventory refresh" settting and things seemed to be fine. However after a relog it continued despite the setting being turned on.

**Comment by gbl** [comment]
It will update the recipe list, but only after a while, so you don't accidentially click the wrong recipe if you want to craft the same thing multiple times and run out of material, or new stuff becomes available.

This is controlled by the "Auto update recipe timer" config option, which is 5 seconds by default. Set it to 0 to update recipes after each craft, but beware of misclicks.
