### ISSUE TITLE
bug - shulkers with NBT must be dragged to crafting menu 

### ISSUE THREAD

**Issue by triphora** [gbl/EasierCrafting#39]
![image1](https://i.imgur.com/ifkXHG0.png)
upon click becomes
![image2](https://i.imgur.com/PC2olN7.png)
due to
![nbt](https://i.imgur.com/X08RklW.png)
NBT tags

**Comment by gbl** [comment]
Fixed in 1.7, the `BlockEntityTag` tag (which is used by shulker boxes to store items) doesn't prevent them from being recipe ingredients any more.
