### ISSUE TITLE
When crafting honey blocks, only one set of max can be created at a time.

### ISSUE THREAD

**Issue by end-user** [gbl/EasierCrafting#42]
If you have a full inventory of honey bottles and attempt to make the max number of honey blocks possible, you can only do this once despite having enough bottles to do it repeatedly.  Other items do not behave this way; bamboo to sticks for example.

**Comment by frankhta** [comment]
can confirm that honey bottles are only craftable one bottle at a time so in other words 4  bottle cos it takes 4 bottles to craft 1

**Comment by Kylebartaous** [comment]
I've noticed this also. Then having a full inventory of honey bottles, & you try to do, craft as many are you can, it would only craft about 16 blocks of honeys, 60 empty bottles get left in the inventory. 4 empty bottle seem to get stuck in the crafting table, so what the mod may need to do as a special case, clear the crafting bench twice then it crafts.
![2021-08-03_04 29 25](https://user-images.githubusercontent.com/11208209/128008082-a3bab128-148e-4726-ad7f-2c2dbda11979.png)

This also happens then crafting honey bottles to honey blocks well in the player's inventory crafting grid.
![2021-08-03_04 39 42](https://user-images.githubusercontent.com/11208209/128009656-2097079a-8a6e-4e0d-ae36-ab99820e2efa.png)

It shows crafting honey blocks back to honey bottles as a shapeless recipe that the player inventory can do, even though it can't.

![2021-08-03_04 51 39](https://user-images.githubusercontent.com/11208209/128010610-7a37f9cf-d962-4865-a8c8-deb76d1c1f93.png)

It also leaves behind a glass bottle in the crafting space then making sugar from honey bottles

**Comment by gbl** [comment]
Yes, honey bottles need special treatment - the game leaves a set of empty bottles in the input slots after crafting the block. This is the game's choice, not mine. Which means the next click won't craft anything anymore as the mod won't try to craft with a half-filled input grid.

I added a special case for this in 1.7 - after crafting a honey block, I send four more shift-clicks to the input slots, which should remove the empty bottles from there.
