### ISSUE TITLE
Bug: 1.17.1 (Fabric) netherrite recipe shows as shapeless recipe

### ISSUE THREAD

**Issue by Kylebartaous** [gbl/EasierCrafting#44]
Minecraft version: 1.17.1
Fabric API version: 0.37.1+1.17
Fabric loader version: 0.11.6
Easier crafting mod version: 1.17.1-fabric0.36.1-1.6.7

I noticed then doing some crafting of Netherrite ingots would show up are craft-able in the players inventory, 2 by 2 even then it can't craft it, as a shapeless recipe. This was tried then playing on a vanilla / paper server w/ plugins, though the server doesn't have any plugins that extend the size of the crafting table, & i was not using the /workbench command that would give you a gui version of a 3 x 3.
![2021-08-03_03 50 24](https://user-images.githubusercontent.com/11208209/128004017-dcd8e9f3-6df8-4382-8e61-5b083e49d0da.png)
![2021-08-03_03 54 28](https://user-images.githubusercontent.com/11208209/128004064-4a396a00-017d-48b1-9537-d17c2e13e4b5.png)

**Comment by ghost** [comment]
> 
> 
> Minecraft version: 1.17.1
> Fabric API version: 0.37.1+1.17
> Fabric loader version: 0.11.6
> Easier crafting mod version: 1.17.1-fabric0.36.1-1.6.7
> 
> I noticed then doing some crafting of Netherrite ingots would show up are craft-able in the players inventory, 2 by 2 even then it can't craft it, as a shapeless recipe. This was tried then playing on a vanilla / paper server w/ plugins, though the server doesn't have any plugins that extend the size of the crafting table, & i was not using the /workbench command that would give you a gui version of a 3 x 3.
> ![2021-08-03_03 50 24](https://user-images.githubusercontent.com/11208209/128004017-dcd8e9f3-6df8-4382-8e61-5b083e49d0da.png)
> ![2021-08-03_03 54 28](https://user-images.githubusercontent.com/11208209/128004064-4a396a00-017d-48b1-9537-d17c2e13e4b5.png)

Kyle, why did you fire-grief month's worth of projects, kill people's animals and villagers, and completely ruin spawn on the UTDS Experimental Snapshot server earlier?  That wasn't very nice.  An instructive error.  ;)  It begins.

**Comment by gbl** [comment]
Fixed in version 1.7  which I just uploaded to CF and Modrinth.
