### ISSUE TITLE
Suggestions: add portable crafting pad hotkley and ability to put into Tinker slots

### ISSUE THREAD

**Issue by lospejos** [gbl/EasierCrafting#46]
Hi! If it is possible, please add:
1) portable crafting pad hotkley (to bring it using hotkey)
2) ability to put portable crafting pad into Tinker slots
Thanks

**Comment by gbl** [comment]
Sorry, but no - EasierCrafting is intended to work client side, without any server support. Your ideas can't be done without server support.
