### ISSUE TITLE
Crash with FAPI 0.46.0

### ISSUE THREAD

**Issue by catgirldoll** [gbl/EasierCrafting#49]
When loading a fresh 1.18.1 instance with:
 - FML 0.12.12
 - FAPI 0.46.0+1.18
 - EC 1.18-fabric0.43.1-1.7
 
 the game crashes with the following log: [crash log](https://paste.ee/p/9z8B4)
 
 The game launches normally in the same instance, with the older FAPI 0.45.2+1.18. [normal log](https://paste.ee/p/sifvu)

**Comment by gbl** [comment]
Thanks for reporting this! Should be fixed in the 1.18.1 version which I just published on Curseforge and Modrinth.
