### ISSUE TITLE
Will not launch - 1.18.2

### ISSUE THREAD

**Issue by catgirldoll** [gbl/EasierCrafting#52]
Please update EasierCrafting to 1.18.2 - the previous mod version is incompatible.
MC version: `1.18.2`
Fabric version: `0.13.3`
Fabric API version: `fabric-api-0.47.10+1.18.2.jar`
Mod version: `easiercrafting-1.18.1-fabric0.45.0-1.7.jar`
[crash log](https://paste.ee/p/E7HU6)
[dxdiag](https://paste.ee/p/wOh0a)

Thanks <3

**Comment by triphora** [comment]
https://cdn.discordapp.com/attachments/745979270748307458/933935018605150238/easiercrafting-22w03a-fabric0.46.2-1.7.jar
https://cdn.discordapp.com/attachments/745979270748307458/951938158893858876/crowdin-translate-1.41.18.2.jar

Temporary replacement before @gbl can get to merging #50 and gbl/crowdintranslate#15 and making releases out of them.

**Comment by catgirldoll** [comment]
Can confirm this works. Thank you Emma, you're a saint <3

**Comment by gbl** [comment]
Updated version for 1.18.2 pushed to CF and Modrinth.
