### ISSUE TITLE
Items despawning after death

### ISSUE THREAD

**Issue by Flintley** [gbl/EasierCrafting#59]
When I die, 1 kind of items despawns. In the death screen you can see the item in your hand which will dissapear after respawn.
Please fix it, its very annoying in skyblock. All my saplings are now disappeared. Sorry for my bad english.

**Comment by end-user** [comment]
Despawning is part of the game and unrelated to this mod.

**Comment by Flintley** [comment]
No, it disappears and isn't dropping. It's just gone and all other Items are dropped.

**Comment by end-user** [comment]
> No, it disappears and isn't dropping. It's just gone and all other Items are dropped.

You mis-understand: "EasierCrafting" has nothing to do with your items despawning.
