### ISSUE TITLE
Re-dying Shulkers

### ISSUE THREAD

**Issue by beerswain** [gbl/EasierCrafting#70]
Hi! Apologies if this was already dealt with and I just am not seeing it.

When dying shulkers, I noticed today that even if I have, say, six red shulkers and six undyed shulkers in my inventory, and click to make a yellow shulker, it will redye one of the red shulkers rather than using one of the undyed shulkers. Bug, or feature?

**Comment by gbl** [comment]
Not a bug, Maybe a feature that isn't desirable in this specfic situation.

Whenever you click a recipe, it tries to satisfy the ingredients from any available materials - for example, if you craft a chest, the mod will look for any types of planks to craft it from. But there's no priority selection.

I could allow only undyed shulkers as inputs for the shulker dyeing recipe, but if you have exactly one red shulker in your inventory and nothing else, and click the yellow recipe, you probably want to re-dye the red one. So doing that would just make people complain the other way round.

Which means you should handle this the way all recipes work - if you have birch planks and oak planks in your inventory, craft a chest, and want to make sure the birch planks get used, put the oak planks away first.
