### ISSUE TITLE
Crash on double tapping inventory button

### ISSUE THREAD

**Issue by stw222** [gbl/EasierCrafting#8]
[https://pastebin.com/wwm0SL70](https://pastebin.com/wwm0SL70)

When i double tap E quickly, the same says saving world (even though I'm on a server) and crashes

Mods Folder screenshot
[https://imgur.com/a/oM9kR06](https://imgur.com/a/oM9kR06)

**Comment by gbl** [comment]
Oh wow. You need to type really fast for this to happen, I wasn't able to get it buy just holding the E key on autorepeat. It happens when the second keypress is before the extended gui has been drawn the first time, in this case the search textfield is null and the check if it's focused fails.

**Comment by gbl** [comment]
Should be fixed with beta3 which I just released here: https://github.com/gbl/EasierCrafting/releases/tag/1.13.2-1.3beta3

Please tell mix if this fixes the bug for you; if it does, I'll update curseforge.

**Comment by stw222** [comment]
ya there's sometimes i kind of think about what i do next before i have done the previous thing i though about. kinda the case when i double tap e. I'm like i need to do something but then decide, no i need to look in this chest real quick.

**Comment by stw222** [comment]
looks like the problem is fixed
